### ISSUE TITLE
Please update Ubuntu PPA packages (https://launchpad.net/~gezakovacs/+archive ) to latest GIT commit - currently debs doesn't start in Ubuntu 18.04

### ISSUE THREAD

**Issue by Baltix** [unetbootin/unetbootin-debian#1]
Please update Ubuntu PPA packages (https://launchpad.net/~gezakovacs/+archive ) to latest GIT commit - there is a fix for https://github.com/unetbootin/unetbootin/issues/177
Currently unetbootin in your PPA is older and currently doesn't start in Ubuntu 18.04
Thanks

**Comment by gkovacs** [comment]
this issue was fixed last year :)
